"""
3D constructed target: cation doublet + per-direction bridge pairs.

Orbitals per cell (8):
    0,1        A doublet (the n_phi=2 pairing manifold)
    2+2d,3+2d  two bridge orbitals for direction d in {x,y,z}
               physically: the anion's sigma and one pi orbital on that bond

Each bridge B connects A_i and A_{i+d}. Two bridge flavours per direction with
a relative orbital rotation phi generate the sigma-winding; the 1D case showed
this is what produces M = n^2/4 with n>1 from purely nearest-neighbour bonds.

Per-direction rotation AXES are taken distinct (x-bonds rotate in the
sx-sy plane, y-bonds in sy-sz, z-bonds in sz-sx) so the three directions wind
in different planes and their metric contributions add rather than cancel.
"""
import numpy as np

SX = np.array([[0, 1], [1, 0]], complex)
SY = np.array([[0, -1j], [1j, 0]], complex)
SZ = np.array([[1, 0], [0, -1]], complex)
I2 = np.eye(2, dtype=complex)
NORB = 8


def _rot(axis, ang):
    """SU(2)-style real rotation of a 2-spinor, generated by a Pauli axis."""
    P = {'xy': SZ, 'yz': SX, 'zx': SY}[axis]
    return np.cos(ang / 2) * I2 - 1j * np.sin(ang / 2) * P


def hk3(K, t_ab=1.0, eps_b=2.0, t_d=0.0, phi=0.8 * np.pi, aniso=(1.0, 1.0, 1.0)):
    """K shape (...,3) in units of 2pi/a. Returns (...,8,8)."""
    sh = K.shape[:-1]
    H = np.zeros(sh + (NORB, NORB), complex)
    w = np.array([1, 1], complex) / np.sqrt(2)
    wp = np.array([1, -1], complex) / np.sqrt(2)
    planes = ['xy', 'yz', 'zx']
    for d in range(3):
        Rr = _rot(planes[d], phi)
        pairs = [(w, wp), (Rr @ w, Rr @ wp)]
        ph = np.exp(-1j * K[..., d])
        td_ = t_ab * aniso[d]
        for j, (v, vp) in enumerate(pairs):
            col = 2 + 2 * d + j
            for a in range(2):
                H[..., a, col] += td_ * np.conj(v[a])
                H[..., col, a] += td_ * v[a]
                H[..., a, col] += td_ * np.conj(vp[a]) * ph
                H[..., col, a] += td_ * vp[a] * np.conj(ph)
            H[..., col, col] = eps_b
        if t_d:
            H[..., :2, :2] += 2 * t_d * np.cos(K[..., d])[..., None, None] * I2
    return H


def analyse3(t_ab=1.0, eps_b=2.0, t_d=0.0, phi=0.8*np.pi, nk=20, bands=(0,1), aniso=(1.,1.,1.)):
    k = 2 * np.pi * (np.arange(nk) + 0.5) / nk
    K = np.stack(np.meshgrid(k, k, k, indexing='ij'), axis=-1)
    dk = 2 * np.pi / nk
    E, V = np.linalg.eigh(hk3(K, t_ab, eps_b, t_d, phi, aniso))
    out = []
    for b in bands:
        u = V[..., :, b]
        P = np.einsum('...i,...j->...ij', u, u.conj())
        trg = np.zeros(P.shape[:-2])
        for i in range(3):
            dP = (np.roll(P, -1, i) - np.roll(P, 1, i)) / (2 * dk)
            trg += 0.5 * np.real(np.einsum('...ij,...ji->...', dP, dP))
        rho = np.abs(u) ** 2
        rf = rho.reshape(-1, NORB)
        A = (rf.T @ rf) / rf.shape[0]
        others = [m for m in range(NORB) if m != b]
        gap = min(float(np.abs(E[..., m] - E[..., b]).min()) for m in others)
        out.append(dict(band=b, W=float(E[..., b].max() - E[..., b].min()),
                        M=float(trg.mean()), lam=float(np.linalg.eigvalsh(A)[-1]),
                        gap=gap, wA=float(rf[:, :2].sum(1).mean()),
                        Emin=float(E[..., b].min()), Emax=float(E[..., b].max())))
    return out


KB = 0.086173e-3
COEF3 = 0.55 * 0.67


def tc_of(b, t_ab_eV, U_phys=1.5):
    """Tc in K. Model energies are in units of t_ab; t_ab_eV sets the scale."""
    U = min(b['gap'] / 2 * t_ab_eV, U_phys)
    amp = b['lam'] / 4.0
    stf = COEF3 * b['M']
    return U * min(amp, stf) / KB, ('amp' if amp < stf else 'stiff')
